//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdHippo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserKeywordTag
    {
        public int Id { get; set; }
        public int KeywordId { get; set; }
        public int TagId { get; set; }
        public int UserId { get; set; }
    
        public virtual Keyword Keyword { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual User User { get; set; }
    }
}
