CREATE TABLE [dbo].[UserKeywordTags]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[KeywordId] INT NOT NULL FOREIGN KEY REFERENCES Keywords(Id),
	[TagId] INT NOT NULL FOREIGN KEY REFERENCES Tags(Id),
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES Users(Id)
)
